server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: keycloak
              uri: http://keycloak:8080
              predicates:
                - Path=/realms/easymeal/protocol/openid-connect/token, /realms/easymeal/protocol/openid-connect/certs, /realms/easymeal/.well-known/openid-configuration

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/v1/companies/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**

            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/v1/carts/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payments/**

            - id: shipment-service
              uri: lb://shipment-service
              predicates:
                - Path=/api/v1/shipments/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notifications/**

            - id: review-service
              uri: lb://review-service
              predicates:
                - Path=/api/v1/reviews/**

            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/v1/cs/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/easymeal

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:eureka-server}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info
